import './globals.css'
import { Inter } from 'next/font/google'
import TopNavigation from "../components/nav/nav";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Exe.lk',
  description: 'Generated by Exe.lk Software Development Team.',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <TopNavigation/>
      {children}
      </body>
    </html>
  )
}
